### ISSUE TITLE
Event Creator Functionalities Doesn't Work (Yet?)

### ISSUE THREAD

**Issue by ApolloZhu** [aroundu403/AroundU#11]
**Describe the bug**

Can't get to the event creation page.

**To Reproduce**
1. Go to https://aroundu-403.web.app/#/
2. Log in
3. Click on + button on the bottom of the home page
4. Nothing happens

**Expected behavior**

It will lead me to the event create page.

**Desktop**
 - OS: macOS
 - Browser: Chrome

**Additional context**

> You can click on the [??] located on the bottom of the home page

Probably missing something at where `[??]` is in UserManual.md

**Comment by JinghuaWang** [comment]
Hi Apollo,

We are currently developing the create event page. It would be available in the final release. Thanks for letting us know that the user story is still incomplete.

**Comment by JinghuaWang** [comment]
I am going to leave this issue open so other reviewers can see this issue.

**Comment by JinghuaWang** [comment]
We have implemented the features for event creators! Closing this issue now.
