### ISSUE TITLE
Issues Connecting to Database While Setting Up with Windows

### ISSUE THREAD

**Issue by Eado51415** [aroundu403/AroundU#12]
**Describe the bug**
I wasn't able to connect to the database successfully because I lacked the credentials/ was not able to successfully set the credentials.  I worked with John to diagnose the issue.

**To Reproduce**
1. I added DB_NAME, DB_PASS, DB_TEST_NAME, DB_USER and INSTANCE_CONNECTION_NAME to my environment variables in Windows
2. I opened up a new git bash window, navigated to the backend folder, then ran mvn clean, mvn compile and mvn verify -Psurefire 
3. The last command gave me the errors

**Expected behavior**
Expected to pass integration tests

**Screenshots**
![image](https://user-images.githubusercontent.com/104041462/170187399-f8de8ea8-b56c-4ca1-9156-e042059eb576.png)
![image](https://user-images.githubusercontent.com/104041462/170187435-5f78e512-419c-4ae9-8a4d-e229c3d6dceb.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
Ran commands with Git Bash

**Additional context**
According to John these steps seems to be much more difficult on Windows vs Mac. It might be useful to add a Windows setup section within the documentation later.

**Comment by wzhang88** [comment]
Thank you for posting this issue! We will work on this.

**Comment by JinghuaWang** [comment]
Added more instructions for setting up on Windows.
