### ISSUE TITLE
Faulty render on Create Event page

### ISSUE THREAD

**Issue by yixiaoliuw** [aroundu403/AroundU#15]
**Create Event page layout rendering bug**
When trying to delete an input to the time input box, the page renders a faulty layout and shows the faulty layout to the user.

**To Reproduce**
1. Click on the "+" button on the map page.
2. In the Data&Time section, click on the Date box for the Start section, then click Done to add the input.
3. In the Date&Time section, click on the Time box for the Start section, then click Done to add the input.
4. Click delete keyboard button to delete the input in the Time box.
5. See error

**Expected behavior**
The page layout should remain the same as initial and the Time input box should be cleared of any input.

**Screenshots**
<img width="1544" alt="Screen Shot 2022-06-02 at 12 09 31 PM" src="https://user-images.githubusercontent.com/56842311/171718564-40bae881-ac74-4ef0-97ff-b61b27229084.png">
<img width="1544" alt="Screen Shot 2022-06-02 at 12 09 47 PM" src="https://user-images.githubusercontent.com/56842311/171718651-fcdf1995-946e-40b2-9b8e-621a2f7ac0e2.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: chrome

**Additional context**

**Comment by JinghuaWang** [comment]
The UI behavior was designed for iOS devices. On mobile devices, users won't have access to the keyboard and couldn't modify the content of the DateTime picker.

Changed the datetime picker to be read-only so that users won't be able to interact with the DateTime picker with the keyboard.
