### ISSUE TITLE
Not able to sign out 

### ISSUE THREAD

**Issue by JinghuaWang** [aroundu403/AroundU#4]

**Comment by JinghuaWang** [comment]
Can't sign out once users sign in.

**Comment by JinghuaWang** [comment]
The sign out button is temporarily placed on the list view page.
Will migrate to profile page once we have it.

**Comment by ApolloZhu** [comment]
Feedback: I am able to sign out using the sign out button, maybe rename the issue title to reflect the current status

**Comment by JinghuaWang** [comment]
Update status
