### ISSUE TITLE
Should Use Issue Template

### ISSUE THREAD

**Issue by ApolloZhu** [aroundu403/AroundU#6]
- An description summary of what goes wrong: There's a requirement on what information to include in issue report, but there's no template provided when creating an issue
- Which platform you are using?: GitHub
- Which page you see the issue?: GitHub Issues
- What kinds of issue? Application Crashed? Rendering Error? Functional Issue?: Suggestion
- Steps to reproduce the bug:
   - What are the list of steps that leads you to issue?
      1. Reader user documentation on how to create a new issue
      2. Create a new Issue
   - Is the error repeatable?: Yes
   - List out the steps to guide us to find the bug!
      - **Do I need to repeat this again?**
- What are you expecting?
   - There's some template I can fill out, something like https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests
- What actually happened?
   - Issues is entirely blank

**Comment by JinghuaWang** [comment]
Apollo,

Thank you so much for pointing us to the Github issue template. We had trouble finding the entry point for setting it up. We appreciate your genuine suggestion.

**Comment by JinghuaWang** [comment]
Added GitHub issue template. Closing this issue.
